#ifndef _JLOS_CONFIG_H
#define _JLOS_CONFIG_H

#define KERNEL_CONFIG_ARCH_X86    0
#define KERNEL_CONFIG_ARCH_ARM    1
#define KERNEL_CONFIG_ARCH_RISCV  2

#define KERNEL_CONFIG_HARDWARE_ARCH  KERNEL_CONFIG_ARCH_X86

#define KERNEL_CONFIG_PREEMPTIVE        1

/* ====== 功能开关 ====== */
#define KERNEL_CONFIG_DEBUG_CONSOLE     1

#define KERNEL_CONFIG_DEBUG_NETWORK     1
#define KERNEL_CONFIG_DEBUG_MEMORY      1
#define KERNEL_CONFIG_ENABLE_TESTS      1
#define KERNEL_CONFIG_DEBUG_LOG         1

#define JLOS_KERNEL_DEBUG               1
#define JLOS_KERNEL_LOG_FUNC            0
#define JLOS_KERNEL_LOG_PRINT_LEVEL     0
#define JLOS_KERNEL_LOG_PRINT_SUBSYS    0

#endif
