#ifndef __JLOS_CONFIG_H
#define __JLOS_CONFIG_H

#define KERNEL_CONFIG_DEBUG_CONSOLE 1
#define KERNEL_CONFIG_DEBUG_NETWORK 1
#define KERNEL_CONFIG_ENABLE_TESTS 1
#define KERNEL_CONFIG_DEBUG_LOG 1

#endif
